[2022-07-12 01:04:19,447] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bitcoin.parse_tuple manual__2022-07-12T01:04:17.488788+00:00 [queued]>
[2022-07-12 01:04:19,466] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bitcoin.parse_tuple manual__2022-07-12T01:04:17.488788+00:00 [queued]>
[2022-07-12 01:04:19,466] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 01:04:19,467] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-12 01:04:19,467] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 01:04:19,515] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parse_tuple> on 2022-07-12 01:04:17.488788+00:00
[2022-07-12 01:04:19,522] {standard_task_runner.py:52} INFO - Started process 4687 to run task
[2022-07-12 01:04:19,528] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'bitcoin', 'parse_tuple', 'manual__2022-07-12T01:04:17.488788+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/projeto_api.py', '--cfg-path', '/tmp/tmpgtvjuryd', '--error-file', '/tmp/tmp3h9op090']
[2022-07-12 01:04:19,528] {standard_task_runner.py:80} INFO - Job 27: Subtask parse_tuple
[2022-07-12 01:04:19,651] {task_command.py:370} INFO - Running <TaskInstance: bitcoin.parse_tuple manual__2022-07-12T01:04:17.488788+00:00 [running]> on host 54ef6f590a3a
[2022-07-12 01:04:19,982] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin
AIRFLOW_CTX_TASK_ID=parse_tuple
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T01:04:17.488788+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T01:04:17.488788+00:00
[2022-07-12 01:04:19,983] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: to_tuple() missing 1 required positional argument: 'data'
[2022-07-12 01:04:20,018] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin, task_id=parse_tuple, execution_date=20220712T010417, start_date=20220712T010419, end_date=20220712T010420
[2022-07-12 01:04:20,057] {standard_task_runner.py:97} ERROR - Failed to execute job 27 for task parse_tuple (to_tuple() missing 1 required positional argument: 'data'; 4687)
[2022-07-12 01:04:20,079] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 01:04:20,168] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
