[2022-07-12 01:09:24,393] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bitcoin.parse_tuple manual__2022-07-12T01:09:21.849934+00:00 [queued]>
[2022-07-12 01:09:24,420] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bitcoin.parse_tuple manual__2022-07-12T01:09:21.849934+00:00 [queued]>
[2022-07-12 01:09:24,421] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 01:09:24,421] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-12 01:09:24,421] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 01:09:24,474] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parse_tuple> on 2022-07-12 01:09:21.849934+00:00
[2022-07-12 01:09:24,485] {standard_task_runner.py:52} INFO - Started process 4898 to run task
[2022-07-12 01:09:24,492] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'bitcoin', 'parse_tuple', 'manual__2022-07-12T01:09:21.849934+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/projeto_api.py', '--cfg-path', '/tmp/tmpozcg7qjn', '--error-file', '/tmp/tmpvnvjhtbq']
[2022-07-12 01:09:24,492] {standard_task_runner.py:80} INFO - Job 30: Subtask parse_tuple
[2022-07-12 01:09:24,612] {task_command.py:370} INFO - Running <TaskInstance: bitcoin.parse_tuple manual__2022-07-12T01:09:21.849934+00:00 [running]> on host 54ef6f590a3a
[2022-07-12 01:09:24,818] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin
AIRFLOW_CTX_TASK_ID=parse_tuple
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T01:09:21.849934+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T01:09:21.849934+00:00
[2022-07-12 01:09:24,840] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_bitcoin.py", line 24, in to_tuple
    data_form = ast.literal_eval(posts)
  File "/usr/local/lib/python3.7/ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "/usr/local/lib/python3.7/ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "/usr/local/lib/python3.7/ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "/usr/local/lib/python3.7/ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: ['{"date":"2022-07-10","opening":112650.51249518,"closing":108864.65169488,"lowest":108394.36,"highest":112908.99738712,"volume":"3293926.47888429","quantity":"29.77558944","amount":2602,"avg_price":110625.06371273}']
[2022-07-12 01:09:24,856] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin, task_id=parse_tuple, execution_date=20220712T010921, start_date=20220712T010924, end_date=20220712T010924
[2022-07-12 01:09:24,895] {standard_task_runner.py:97} ERROR - Failed to execute job 30 for task parse_tuple (malformed node or string: ['{"date":"2022-07-10","opening":112650.51249518,"closing":108864.65169488,"lowest":108394.36,"highest":112908.99738712,"volume":"3293926.47888429","quantity":"29.77558944","amount":2602,"avg_price":110625.06371273}']; 4898)
[2022-07-12 01:09:24,914] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 01:09:24,994] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
