[2022-07-12 01:20:38,622] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bitcoin.parse_tuple manual__2022-07-12T01:20:34.417096+00:00 [queued]>
[2022-07-12 01:20:38,647] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bitcoin.parse_tuple manual__2022-07-12T01:20:34.417096+00:00 [queued]>
[2022-07-12 01:20:38,652] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 01:20:38,653] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-12 01:20:38,653] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 01:20:38,700] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parse_tuple> on 2022-07-12 01:20:34.417096+00:00
[2022-07-12 01:20:38,707] {standard_task_runner.py:52} INFO - Started process 5365 to run task
[2022-07-12 01:20:38,716] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'bitcoin', 'parse_tuple', 'manual__2022-07-12T01:20:34.417096+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/projeto_api.py', '--cfg-path', '/tmp/tmp70k3fkzu', '--error-file', '/tmp/tmpeu6313fz']
[2022-07-12 01:20:38,716] {standard_task_runner.py:80} INFO - Job 42: Subtask parse_tuple
[2022-07-12 01:20:38,828] {task_command.py:370} INFO - Running <TaskInstance: bitcoin.parse_tuple manual__2022-07-12T01:20:34.417096+00:00 [running]> on host 54ef6f590a3a
[2022-07-12 01:20:39,012] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin
AIRFLOW_CTX_TASK_ID=parse_tuple
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T01:20:34.417096+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T01:20:34.417096+00:00
[2022-07-12 01:20:39,030] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_bitcoin.py", line 26, in to_tuple
    for key, value in ele:
ValueError: not enough values to unpack (expected 2, got 1)
[2022-07-12 01:20:39,044] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin, task_id=parse_tuple, execution_date=20220712T012034, start_date=20220712T012038, end_date=20220712T012039
[2022-07-12 01:20:39,088] {standard_task_runner.py:97} ERROR - Failed to execute job 42 for task parse_tuple (not enough values to unpack (expected 2, got 1); 5365)
[2022-07-12 01:20:39,136] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 01:20:39,209] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
