[2022-07-12 01:30:06,332] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bitcoin.parse_tuple manual__2022-07-12T01:30:02.378132+00:00 [queued]>
[2022-07-12 01:30:06,355] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bitcoin.parse_tuple manual__2022-07-12T01:30:02.378132+00:00 [queued]>
[2022-07-12 01:30:06,355] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 01:30:06,355] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-12 01:30:06,355] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 01:30:06,395] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parse_tuple> on 2022-07-12 01:30:02.378132+00:00
[2022-07-12 01:30:06,400] {standard_task_runner.py:52} INFO - Started process 5765 to run task
[2022-07-12 01:30:06,404] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'bitcoin', 'parse_tuple', 'manual__2022-07-12T01:30:02.378132+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/projeto_api.py', '--cfg-path', '/tmp/tmpqlruj1i9', '--error-file', '/tmp/tmpz5vgtjoh']
[2022-07-12 01:30:06,405] {standard_task_runner.py:80} INFO - Job 46: Subtask parse_tuple
[2022-07-12 01:30:06,485] {task_command.py:370} INFO - Running <TaskInstance: bitcoin.parse_tuple manual__2022-07-12T01:30:02.378132+00:00 [running]> on host 54ef6f590a3a
[2022-07-12 01:30:06,609] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin
AIRFLOW_CTX_TASK_ID=parse_tuple
AIRFLOW_CTX_EXECUTION_DATE=2022-07-12T01:30:02.378132+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-12T01:30:02.378132+00:00
[2022-07-12 01:30:06,621] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_bitcoin.py", line 23, in to_tuple
    dictionary = {k:v[0] for k,v in posts.items()}
AttributeError: 'list' object has no attribute 'items'
[2022-07-12 01:30:06,648] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin, task_id=parse_tuple, execution_date=20220712T013002, start_date=20220712T013006, end_date=20220712T013006
[2022-07-12 01:30:06,683] {standard_task_runner.py:97} ERROR - Failed to execute job 46 for task parse_tuple ('list' object has no attribute 'items'; 5765)
[2022-07-12 01:30:06,697] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-12 01:30:06,749] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
